# Generated by Django 3.1.2 on 2020-11-13 13:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ed', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Informations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.CharField(max_length=128)),
                ('text', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Subdirections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_direction', models.CharField(max_length=128)),
                ('name_subdirection', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Personals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('experience', models.CharField(max_length=64)),
                ('photo', models.ImageField(upload_to='')),
                ('about_text', ckeditor.fields.RichTextField()),
                ('cur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique_app.courses')),
                ('ed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique_app.educations')),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique_app.events')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique_app.informations')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsSubDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=128)),
                ('subdirection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique_app.subdirections')),
            ],
        ),
        migrations.CreateModel(
            name='InfoDirections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_row', models.CharField(max_length=256)),
                ('info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique_app.informations')),
            ],
        ),
    ]
