# Generated by Django 3.1.2 on 2020-11-13 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinique_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SubAddDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SubDirectionsStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdirections', models.CharField(max_length=256)),
                ('subdir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique_app.subadddirection')),
            ],
        ),
        migrations.CreateModel(
            name='DirectionsStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directions', models.CharField(max_length=256)),
                ('dir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique_app.adddirection')),
            ],
        ),
        migrations.AddField(
            model_name='personals',
            name='add_direction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinique_app.adddirection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personals',
            name='add_subdirection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinique_app.subadddirection'),
            preserve_default=False,
        ),
    ]
