# Generated by Django 3.1.2 on 2020-11-13 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinique_app', '0002_auto_20201113_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='staff',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educations',
            name='staff',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='staff',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EventsItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=256)),
                ('events_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique_app.events')),
            ],
        ),
        migrations.CreateModel(
            name='EducationItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=256)),
                ('ed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique_app.educations')),
            ],
        ),
        migrations.CreateModel(
            name='CoursesItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=256)),
                ('courses_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique_app.courses')),
            ],
        ),
    ]
