# Generated by Django 3.1.2 on 2020-11-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinique_app', '0003_auto_20201113_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='text',
        ),
        migrations.RemoveField(
            model_name='educations',
            name='ed',
        ),
        migrations.RemoveField(
            model_name='events',
            name='text',
        ),
    ]
