# Generated by Django 3.1.2 on 2020-11-13 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinique_app', '0004_auto_20201113_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionStaffItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SubDirectionStaffItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RenameField(
            model_name='directionsstaff',
            old_name='directions',
            new_name='direction',
        ),
        migrations.RenameField(
            model_name='subdirectionsstaff',
            old_name='subdirections',
            new_name='subdirection',
        ),
        migrations.RemoveField(
            model_name='directionsstaff',
            name='dir',
        ),
        migrations.RemoveField(
            model_name='subdirectionsstaff',
            name='subdir',
        ),
        migrations.AlterField(
            model_name='personals',
            name='add_direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique_app.directionsstaff'),
        ),
        migrations.AlterField(
            model_name='personals',
            name='add_subdirection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique_app.subdirectionsstaff'),
        ),
        migrations.DeleteModel(
            name='AddDirection',
        ),
        migrations.DeleteModel(
            name='SubAddDirection',
        ),
        migrations.AddField(
            model_name='subdirectionstaffitems',
            name='subdir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique_app.subdirectionsstaff'),
        ),
        migrations.AddField(
            model_name='directionstaffitems',
            name='dir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique_app.directionsstaff'),
        ),
    ]
