# Generated by Django 3.1.2 on 2020-11-13 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinique_app', '0005_auto_20201113_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directionsstaff',
            old_name='direction',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='directionstaffitems',
            old_name='name',
            new_name='direction',
        ),
        migrations.RenameField(
            model_name='subdirectionsstaff',
            old_name='subdirection',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='subdirectionstaffitems',
            old_name='name',
            new_name='subdirection',
        ),
    ]
