# Generated by Django 3.1.2 on 2020-11-16 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinique_app', '0008_servicedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetail',
            name='part_name',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='session_price1',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='session_price2',
        ),
        migrations.CreateModel(
            name='SessionPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=128)),
                ('session_price1', models.DecimalField(decimal_places=2, max_digits=9)),
                ('session_price2', models.DecimalField(decimal_places=2, max_digits=9)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique_app.servicedetail')),
            ],
        ),
    ]
