# Generated by Django 3.1.2 on 2020-11-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique_app', '0010_auto_20201116_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetail',
            name='img',
        ),
        migrations.AddField(
            model_name='serviceslist',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
