# Generated by Django 3.1.2 on 2020-11-17 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinique_app', '0011_auto_20201116_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_display', models.CharField(max_length=128)),
                ('preview_date', models.DateField()),
                ('preview_title', models.CharField(max_length=128)),
                ('preview_description', models.CharField(max_length=256)),
                ('post_title', models.CharField(max_length=128)),
                ('post_text', models.CharField(max_length=1024)),
                ('post_result_uptext', models.CharField(max_length=512)),
                ('post_result_downtext', models.CharField(max_length=512)),
                ('post_effect', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='PromoResultPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_result_point', models.CharField(max_length=256)),
                ('post_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique_app.promo')),
            ],
        ),
        migrations.CreateModel(
            name='PromoPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=128)),
                ('session_price1', models.DecimalField(decimal_places=2, max_digits=9)),
                ('session_price2', models.DecimalField(decimal_places=2, max_digits=9)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique_app.promo')),
            ],
        ),
    ]
