# Generated by Django 3.1.2 on 2020-11-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique_app', '0012_promo_promoprices_promoresultpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
