# Generated by Django 3.1.2 on 2020-11-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique_app', '0013_promo_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promo',
            old_name='img',
            new_name='post_img',
        ),
        migrations.AddField(
            model_name='promo',
            name='preview_img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
