# Generated by Django 3.1.2 on 2020-11-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique_app', '0014_auto_20201117_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promo',
            old_name='preview_display',
            new_name='preview_discount_obj',
        ),
        migrations.AddField(
            model_name='promo',
            name='preview_discount',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
