# Generated by Django 3.1.2 on 2020-11-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique_app', '0015_auto_20201117_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='short_img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
