# Generated by Django 3.1.2 on 2020-11-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique_app', '0017_personals_photo_index_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenInst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1024)),
            ],
        ),
    ]
