# Generated by Django 3.1.2 on 2020-11-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique_app', '0019_auto_20201118_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personals',
            name='photo',
            field=models.ImageField(upload_to='personal/'),
        ),
        migrations.AlterField(
            model_name='personals',
            name='photo_index_slider',
            field=models.ImageField(upload_to='personal/slider/'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='post_img',
            field=models.ImageField(upload_to='promo/post_img/'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='preview_discount',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='promo',
            name='preview_img',
            field=models.ImageField(upload_to='promo/preview_img/'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='short_img',
            field=models.ImageField(upload_to='personal/detail/'),
        ),
        migrations.AlterField(
            model_name='serviceslist',
            name='img',
            field=models.ImageField(upload_to='service/'),
        ),
    ]
