# Generated by Django 3.1.2 on 2020-11-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique_app', '0020_auto_20201119_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personals',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='personals',
            name='photo_index_slider',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='promo',
            name='post_img',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='promo',
            name='preview_img',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='short_img',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='serviceslist',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
