# Generated by Django 3.1.2 on 2020-11-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique_app', '0021_auto_20201119_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cat', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=2048)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
