# Generated by Django 3.1.2 on 2020-11-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique_app', '0023_qa'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='num',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
